config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:new]
  resources :weapons
  resources :champions do 
    resources :weapons, only: [:index, :show, :new]
    resources :inventory_items 
  end
  resources :inventory_items

  root 'application#home'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/auth/google_oauth2/callback' => 'sessions#omniauth'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/champion.rb
class Champion < ApplicationRecord
  belongs_to :user 
  has_many :inventory_items 
  has_many :weapons, through: :inventory_items

  validates :name, uniqueness: true
  validates :name, length: {minimum: 3}

  accepts_nested_attributes_for :inventory_items
  accepts_nested_attributes_for :weapons

  # before_validation :cap_champ_name

  # def cap_champ_name 
  #   self.name.titleize if name
  # end 
  
  scope :alpha, -> { order('lower(:name)') }

  RACE = %w{ Human Elf Dwarf Troll Orc Giant Undead Halfling }
  CLASS = %w{ Warrior Ranger Sorceror Rogue Cleric Druid Necromancer Guardian Bard}
  
end

app/models/inventory_item.rb
class InventoryItem < ApplicationRecord
  belongs_to :champion
  belongs_to :weapon

  validates :weapon_name, uniqueness: true
  validates :weapon_name, length: {minimum: 5}

  # before_validation :cap_weapon_name

  # def cap_weapon_name
  #  self.weapon_name.titleize
  # end 

end

app/models/user.rb
class User < ApplicationRecord
  has_many :champions
  has_many :weapons

  has_secure_password
  validates :name, uniqueness: true
  validates :name, presence: true
  validates :name, length: {minimum: 7}
  validates :password, presence: true 
  validates :password, length: {minimum: 7}

  def self.from_omniauth(auth)
    where(name: auth.info.name).first_or_initialize do |user|
      user.name = auth.info.name
      user.password = SecureRandom.hex
    end
  end
end

app/models/weapon.rb
class Weapon < ApplicationRecord
  has_many :inventory_items 
  has_many :champions, through: :inventory_items

  validates :weapon_type, uniqueness: true
  validates :weapon_type, length: {minimum: 3}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?
  helper_method :current_user
  
  def home 
    @hide_header = true 
  end 

  private 

  def current_user 
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end 

  def logged_in?
    !!current_user
  end 

  def authenticate_user 
    if !logged_in?
      redirect_to root_path
    end
  end 

end

app/controllers/champions_controller.rb
require 'pry'
class ChampionsController < ApplicationController
  before_action :find_champion, only: [:show, :edit, :update]

  def index 
    @champions = current_user.champions.all.alpha
  end 

  def show
  end 

  def new 
    @champion = Champion.new
  end 

  def create
    @champion = current_user.champions.build(champion_params)
    if @champion.save
      redirect_to champion_path(@champion)
    else 
      flash[:error] = "Incorrect creation attempt. Please try again."
      redirect_to new_champion_path
    end 
  end

  def edit 
  end 

  def update 
    @champion.update(champion_params)
    redirect_to champion_path(@champion)
  end 

  def destroy
    Champion.find(params[:id]).destroy
    redirect_to champions_path  
  end

  private 

  def champion_params 
    params.require(:champion).permit(:name, :race, :classification, inventory_items_attributes: [:weapon_name, :weapon_id], weapons_attributes: [:weapon_type])
  end 

  def find_champion
    @champion = Champion.find_by(id: params[:id])
  end 

end

app/controllers/inventory_items_controller.rb
class InventoryItemsController < ApplicationController
  
  def show 
    @inventory_item = InventoryItem.find_by_id(params[:id])
  end 

  def new 
    @inventory_item = InventoryItem.new
  end 

  def create
    @inventory_item = InventoryItem.new(inventory_items_params)
    @inventory_item.save ? (redirect_to champion_path(@inventory_item.champion)) : (redirect_to new_champion_inventory_item_path(@inventory_item.champion))
  end 

  def edit 
    @inventory_item = InventoryItem.find_by_id(params[:id])
  end 

  def update
    @inventory_item = InventoryItem.find_by_id(params[:id])
    @inventory_item.update(inventory_items_params)
    redirect_to champion_path(@inventory_item.champion)
  end
  # optional
  def destroy 
  end

  private 

  def inventory_items_params 
    params.require(:inventory_item).permit(:champion_id, :weapon_id, :weapon_name)
  end 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 

  def login
    @user = User.new 
  end 

  def create 
    @user = User.find_by(name: params[:user][:name])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id 
      redirect_to user_path(@user)
    else 
      flash[:error] = "Incorrect login attempt. Please try again."
      redirect_to login_path 
    end 
  end 

  def destroy 
    session.delete :user_id 
    redirect_to root_path
  end 

  def omniauth
    @user = User.from_omniauth(auth)
    @user.save
    session[:user_id] = @user.id
    redirect_to user_path(@user)
  end

  private

  def auth
    request.env['omniauth.auth']
  end

end 

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new 
    @user = User.new 
  end 

  def create 
    @user = User.new(user_params)
    if @user.save 
      session[:user_id] = @user.id 
      redirect_to user_path(@user)
    else 
      render :new 
    end 
  end 

  def show 
    @user = User.find_by_id(params[:id])
  end 

  private 

  def user_params 
    params.require(:user).permit(:name, :password)
  end 

end

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController

  def index 
    @champion = Champion.find_by_id(params[:champion_id])
    @weapons = @champion.weapons.all 
  end 

  def show
    @weapon = Weapon.find_by_id(params[:id])
  end 

  def create 
    @weapon = Weapon.new(weapon_params)
    @weapon.save ? (redirect_to champion_weapons_path(@champion)) : (redirect_to new_weapon_path)
  end

  def destroy
    Weapon.find(params[:id]).destroy 
    redirect_to weapons_path
  end 

  private 

  def weapon_params 
    params.require(:weapon).permit(:weapon_type, inventory_items_attributes: [:weapon_name, :champion_id, :weapon_id], champions_attributes: [:id])
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/champions_helper.rb
module ChampionsHelper
end

app/helpers/inventory_items_helper.rb
module InventoryItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/views/application/home.html.erb
<h1>Welcome to the League of Champions</h1> 
<hr>
<h3>
  <%= link_to "Log In with Google", '/auth/google_oauth2' %><br>
  <br>
  <%= link_to "Login", login_path %><br>
  <br>
  <%= link_to "Sign Up", signup_path %> 
</h3>

app/views/champions/_form.html.erb
<% if @champion.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @champion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: champion, local: true do |f| %> 
  <p class="field_with_errors">
    <%= f.label :name, "Champion Name: " %>
    <%= f.text_field :name %><br>
  </p>
  <br>
  <p>
    <%= f.label :race, "Champion Race:" %>
    <%= f.select :race, Champion::RACE, include_blank: 'Select race', required: true %><br>
  </p>
  <br>
  <p>
    <%= f.label :classification, "Champion Class:" %> 
    <%= f.select :classification, Champion::CLASS, include_blank: 'Select class', required: true %><br>
  </p>
  <br>
  <p>
    <%= f.fields_for :inventory_items, InventoryItem.new do |attr| %>
      <p>
        <%= attr.label :weapon_type, "Weapon Type:" %>
        <%= attr.collection_select(:weapon_id, Weapon.all, :id, :weapon_type, prompt: 'Select weapon type') %><br>
      </p>
      <br>
      <p>
        <%= attr.label "Name Your Weapon:" %>
        <%= attr.text_field :weapon_name %>
      </p>
    <% end %><br>
  </p>
  <p>
    <%= f.submit "Create Champion" %> 
  </p>
<% end %> 

app/views/champions/edit.html.erb
<h1>Edit Your Champion</h1>

<%= render 'form', champion: @champion %> <%= form_with model: champion, local: true do |f| %> 
  <p>
    <%= f.label :name, "Champion Name: " %>
    <%= f.text_field :name %><br>
  </p>
  <br>
  <p>
    <%= f.label :race, "Champion Race:" %>
    <%= f.select :race, Champion::RACE, include_blank: 'Select race', required: true %><br>
  </p>
  <br>
  <p>
    <%= f.label :classification, "Champion Class:" %> 
    <%= f.select :classification, Champion::CLASS, include_blank: 'Select class', required: true %><br>
  </p>
  <br>
    <%= f.submit "Create Champion" %> 
<% end %> 

app/views/champions/index.html.erb
<h1>Your Champions</h1>

<ul>
  <% @champions.each do |champion| %> 
    <li> 
      <p><%= link_to champion.name, champion_path(champion) %></p>
    </li> 
  <% end %> 
</ul> 

<p>
  <%= link_to "Create New Champion", new_champion_path %><br>
</p>

app/views/champions/new.html.erb
<h1>Create a new Champion</h1> 
<%= render 'form', champion: @champion %> 

app/views/champions/show.html.erb
<h1><%= @champion.name %></h1>

<h3><u>Traits</u></h3>
<p>
  Race: <%= @champion.race %><br> 
  <br>
  Class: <%= @champion.classification %><br>
</p>

<h3><u>Weapons</u></h3>
<p>
  <ul>
    <% @champion.inventory_items.each do |weapon| %> 
      <li>
        <p><%= link_to weapon.weapon_name, champion_inventory_item_path(@champion, weapon) %> - <%= link_to "Edit Weapon", edit_champion_inventory_item_path(weapon.champion, weapon) %></p>
      </li>
    <% end %> 
  </ul>
</p>
<br>
<hr>
<p>
  <%= link_to "Create A New Weapon", new_champion_inventory_item_path(@champion) %><br>
  <br>
  <%= link_to "Your Weapons", champion_weapons_path(@champion) %><br>
  <br>
  <%= link_to "Delete Champion", champion_path, method: :delete %><br>
  <br>
  <%= link_to "View All Champions", champions_path %>
</p>

app/views/inventory_items/edit.html.erb
<h1>Edit Your Legendary Weapon</h1>

<%= form_with model: @inventory_item, local: true do |f| %> 
  <p>
    <%= f.label :weapon_name, "Weapon Name:" %> 
    <%= f.text_field :weapon_name %><br>
    <br>
  </p>
  <%= f.submit "Submit Weapon Name" %> 
<% end %> 

app/views/inventory_items/new.html.erb
<h1>Create Your Legendary Weapon</h1> 

<%= render partial: 'layouts/errors', locals: {object: @inventory_item} %> 

<%= form_with model: @inventory_item, local: true do |f| %> 
  <p>
    <%= f.label :weapon_type, "Weapon Type:" %>
    <%= f.collection_select(:weapon_id, Weapon.all, :id, :weapon_type, prompt: 'Select weapon type') %><br>
  </p>
  <%= f.hidden_field :champion_id, value: params[:champion_id] %> 
  <p>
    <%= f.label :weapon_name, "Weapon Name:" %> 
    <%= f.text_field :weapon_name %><br>
  </p>

  <%= f.submit "Submit Weapon Name" %> 
  <br>
<% end %> 

app/views/inventory_items/show.html.erb
<h1><%= @inventory_item.champion.name %></h1>
<p>Weapon Type: <%= @inventory_item.weapon.weapon_type %></p>
<p>Weapon Name: <%= @inventory_item.weapon_name %><p>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h3>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <hr>
  <p>
    <%= link_to "Log Out", logout_path %><br>
    <br>
    <strong>©leagueofchampions 2019</strong>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <h3>League of Champions</h3>
</header>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Leagueofchamps</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" unless @hide_header %>

    <% flash.each do |k, v| %>
      <div class=<%= k %>>
        <p><%= v %></p>
      </div>
    <% end %>

    <%= yield %>

    <%= render "layouts/footer" unless !logged_in?%> 
  </body>
</html>

app/views/users/new.html.erb
<h1>New User Sign Up</h1>

<%= render partial: 'layouts/errors', locals: {object: @user} %> 

<%= form_with model: @user, local: true do |f| %>
  <p> 
    <%= f.label :name, "Your Name:" %> 
    <%= f.text_field :name %><br>
    <br>
  </p>
  <p>
    <%= f.label :password, "Your Password:" %> 
    <%= f.password_field :password %><br>
    <br>
  </p>
  
  <%= f.submit "Sign Up" %>
<% end %> 

app/views/users/show.html.erb
<h1>Greetings, <%= @user.name %></h1>

<p>
  <%= link_to "Your Champions", champions_path %><br>
  <br>
  <%= link_to "Create New Champion", new_champion_path %><br>
</p>

app/views/weapons/index.html.erb
<h1><%= @champion.name %>'s Weapons</h1> 

<ul>
  <% @champion.inventory_items.each do |weapon| %> 
    <li>
      <p><%= weapon.weapon_name %></p>
    </li>
  <% end %> 
</ul> 

<p>
  <%= link_to "Your Champion", champion_path(@champion) %>
</p> 

app/views/weapons/new.html.erb
<h1>Create a New Weapon</h1>

<%= render partial: 'layouts/errors', locals: {object: @weapon} %> 

<%= form_with model: @inventory_item, local: true do |f| %> 
  <p>
    <%= f.label :weapon_type, "Weapon Type:" %>
    <%= f.collection_select(:weapon_id, Weapon.all, :id, :weapon_type, prompt: 'Select weapon type') %><br>
  </p>
  <p>
    <%= f.label "Select the Champion:" %>
    <%= f.collection_select(:champion_id, Champion.all, :id, :name, prompt: 'Select champion') %><br>
  </p>
  <br>
  <%= f.submit "Create Weapon" %> 
<% end %><br>

<%= link_to "Your Weapons", weapons_path %>

app/views/weapons/show.html.erb
<% @weapon.inventory_items.each do |item| %>
  <h1><%= item.weapon_name %></h1> 
<% end %> 

<h3><%= @weapon.weapon_type %></h3><br>
<br>
<hr>

<p>
  <%= link_to "Delete Weapon", weapon_path(@weapon), method: :delete %><br>
  <br>
  <%= link_to "Your Weapons", weapons_path %><br>
  <br>
</p>